version: "3.8"
services:
  superstack:
    build:
      context: ./server
    image: superstack
    container_name: superstack
    environment:
      - PORT=9090
      - CLIENT=http://localhost:8080
    volumes:
      - ./data:/data
    command: sh -c "npm install && npm run dev"
    networks:
      - superstacknet
  superstackproxy:
    build:
      context: ./config
    container_name: superstackproxy
    ports:
      - "8080:80"
    volumes:
      - ./data:/data
      - ./config:/etc/nginx
    networks:
      - superstacknet
  
networks:
  superstacknet:
    driver: bridge
